### ISSUE TITLE
Problem using composer

### ISSUE THREAD

**Issue by tontof** [Level-2/Maphper#25]
I have a problem with ```vendor/autoload.php```:
```
Fatal error: Class '\Maphper\DataSource\sqliteAdapter' not found in vendor/level-2/maphper/maphper/datasource/database.php on line 37
```
It seems to work with mysql. Don't know exactly how it should be corrected. For now I've added a ucfirst to have SqliteAdapter, but I guess there's a better way!

**Comment by garrettw** [comment]
At first I thought that the call to `$pdo->getAttribute()` (in database.php) should be wrapped in a `ucfirst()`, but if mysql works... it just doesn't make sense.
