### ISSUE TITLE
Problem updating some data

### ISSUE THREAD

**Issue by Mr-Chimp** [Level-2/Maphper#31]
So I think I may have found a bug. I have a simple Maphper object based on a reasonably simple table (called songs) and I was able to get the data and loop through it fine but then I realised I had a mistake in some file paths and wanted to try updating the records: (id is the index and $allSongs is the Maphper object)

```
foreach($allSongs as $song) { //echo $song->id;
    $song->thumb_loc = 'NEW_LOCATION';
    $allSongs[$song->id] = $song;
}
```

But the issue is that this generates a load of MySQL errors: "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '50' for key 'PRIMARY' in maphper/datasource/mysqladapter.php"

Doing a bit of debugging and echoing out the sql I can see it is trying to do an insert, then after the error is displayed it is doing an update as expected. 

Thanks

**Comment by Mr-Chimp** [comment]
Just wanted to clarify, the data does get updated correctly as expected, just the insert statements are running and generating those errors. 

Also looks like I can't read and pressed the 'Close issue' button by mistake just now.

**Comment by solleer** [comment]
Try this. This should also work.
```
foreach($allSongs as $song) {
    $song->thumb_loc = 'NEW_LOCATION';
    $allSongs[] = $song;
}
```

**Comment by Mr-Chimp** [comment]
Thanks for that, is quite useful to know. The Integrity constraint violation error came up again when it tried to do an insert but it still did the update all the same so it did work.

**Comment by solleer** [comment]
I looked at the code and he has it do what you said where it tries inserting and catches any PHP errors and if it does then it tries updating

**Comment by Mr-Chimp** [comment]
Ahh that explains why it all still worked even though there were the messages coming up and a somewhat interesting way to get around the problem of knowing whether to insert / update. Thanks for looking at what was going on as a quick fix on my end I think I may just stick an @ symbol in front of the insert line just to keep it quiet in case I need to make any amends in the future. Though I imagine that is ultimately not the best solution.

**Comment by solleer** [comment]
Can this be closed
