### ISSUE TITLE
Maphper not throwing error

### ISSUE THREAD

**Issue by solleer** [Level-2/Maphper#48]
When I insert new data into a table but data for a field is missing that doesn't have a default value, no error is thrown by maphper. Looking into the code with some `var_dump`s it turns out that maphper gets the error from the issue but since it then tries an update afterwards, it gets rid of the error so it appears that the data was inserted into the table when it hasn't.
@TomBZombie I can't think of a good way to solve this and could use some help.

**Comment by solleer** [comment]
@TomBZombie Do you know of a good way to solve this?

**Comment by TomBZombie** [comment]
I need to get all tests passing correctly before looking at anything else unfortunately. I'm pretty sure when the tests were added they passed as expected, I've got to go back through the commits and see what broke them

**Comment by TomBZombie** [comment]
We need to do something different depending on edit mode:


1. If edit mode is on, the table should be edited and remove `NOT NULL`. 

2. If edit mode is off, throw an exception

**Comment by TomBZombie** [comment]
You're right, this is a very difficult problem to catch.

We can detect the relevant error code/message `Field 'col2' doesn't have a default value` but for an update that's fine.

We can't even use `affectedRows` because an `UPDATE` that is valid but doesn't change any records still returns zero.

**Comment by TomBZombie** [comment]
This patch makes my test pass:

```diff
diff --git a/maphper/datasource/database.php b/maphper/datasource/database.php
index 156e7ad..3a9ad1a 100644
--- a/maphper/datasource/database.php
+++ b/maphper/datasource/database.php
@@ -142,7 +142,7 @@ class Database implements \Maphper\DataSource {
                try {
                        $result = $this->insert($this->table, $this->primaryKey, $data);
                        //If there was an error but PDO is silent, trigger the catch block anyway
-                       if ($result->errorCode() !== "00000") throw new \Exception('Could not insert into ' . $this->table);
+                       if ($result->rowCount() === 0) throw new \Exception('Could not insert into ' . $this->table);
                }
                catch (\Exception $e) {
                        if ($tryagain && self::EDIT_STRUCTURE & $this->alterDb) {
@@ -151,8 +151,10 @@ class Database implements \Maphper\DataSource {
                        }
                        else throw $e;
                }
+
                //TODO: This will error if the primary key is a private field
                if ($new && count($this->primaryKey) == 1) $data->{$this->primaryKey[0]} = $this->adapter->lastInsertId();
+
                //Something has changed, clear any cached results as they may now be incorrect
                $this->resultCache = [];
                $pkValue = $data->{$this->primaryKey[0]};
@@ -169,7 +171,8 @@ class Database implements \Maphper\DataSource {
                        $error = 1;
                }
 
-               if ($error || $result->errorCode() !== "00000") $result = $this->adapter->query($this->crudBuilder->update($table, $primaryKey, $data));
+               if ($error || $result->errorCode() !== '00000') $result = $this->adapter->query($this->crudBuilder->update($table, $primaryKey, $data));
+
                return $result;
        }
 }
diff --git a/tests/MySqlDatabaseTest.php b/tests/MySqlDatabaseTest.php
index e1a3951..8aa152c 100644
--- a/tests/MySqlDatabaseTest.php
+++ b/tests/MySqlDatabaseTest.php
@@ -15,6 +15,7 @@ class MySqlDatabaseTest extends PHPUnit_Framework_TestCase {
 
                $this->pdo = new \PDO('mysql:dbname=' . $config->schema . ';host=' . $config->server . ';port=' . $config->port, $config->username, $config->password);
                $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_SILENT);
+               $this->pdo->setAttribute(PDO::MYSQL_ATTR_FOUND_ROWS, true);
        }
 
        protected function getDataSource($name, $primaryKey = 'id', array $options = []) {
@@ -1128,7 +1129,7 @@ class MySqlDatabaseTest extends PHPUnit_Framework_TestCase {
 
                $mapper[] = $record;
 
-               $this->assertEquals(1, count($mapper));
+               $this->assertEquals(0, count($mapper));
 
```

but breaks several other tests. It also requires that the PDO setting `PDO::MYSQL_ATTR_FOUND_ROWS` is true. This makes `rowCount()` return the number of rows matched by an update query, not the number of rows affected.

**Comment by TomBZombie** [comment]
Ok I've got it working. It's not ideal because of a limitation of PDO. To get this to work you must supply 

```php
PDO::MYSQL_ATTR_FOUND_ROWS => TRUE
```

in the constructor for `PDO`. `$pdo->setAttribute` does not work!

Obviously this will have a global effect anywhere the `$pdo` instance is used. Whether that's an issue or not I don't know. 

We could get maphper to issue a  `SELECT `after an `UPDATE` to see if `UPDATE` returned `00000` but did match some rows. I'm not sure we want the overhead of needing a `SELECT` after every `00000` `UPDATE`.

**Comment by TomBZombie** [comment]
The commit above works provided `PDO` is instantiated with `[PDO::MYSQL_ATTR_FOUND_ROWS => true]` in the constructor.

I'm trying to find a different way of reading the number of matched rows but it doesn't seem simple.

**Comment by TomBZombie** [comment]
I've done it using an additional `SELECT`. This additional `SELECT ` is only triggered when `rowCount` is zero so for performance it is advisable to use `PDO::MYSQL_ATTR_FOUND_ROWS => TRUE`, but this will still work if it's not set.
