### ISSUE TITLE
Maphper could benefit from using Netsilik/Struct

### ISSUE THREAD

**Issue by jaccoTopVintage** [Level-2/Maphper#49]
Looking at this project, I noticed it makes quite a lot of use of PHPs `stdClass`.

I think it could benefit from using [Netsilik/Struct](https://github.com/Netsilik/Struct). It would provide more structure, thereby eliminating the possibilities for errors.

**Comment by TomBZombie** [comment]
You can specify any class you like for Maphper to use for mapped entities, whether that's an instance of stdclass, a concrete class definition or a generic struct like the project you mentioned should be down to the developer of the individual project. 

It's a positive feature for maphper that we don't specify how entities are designed, it's down to the developer using the library to decide how the entities are structured. 

With a view to future support mongodb or other document databases, requiring specific structures would be very limiting.
