### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Maphper#51]
I'm not sure what commit broke may of the tests, but the exception `Could not insert into $table` is occurring in  multiple tests

**Comment by TomBZombie** [comment]
Ok so the error I'm getting is actually due to `CREATE TABLE` queries like:

```sql
CREATE TABLE IF NOT EXISTS cast (movieId VARCHAR(255) NOT NULL, actorId VARCHAR(255) NOT NULL, PRIMARY KEY(movieId, actorId)) 
```

And the error is:

```
Error Code: 1709. Index column size too large. The maximum column size is 767 bytes.
```

This seems to be because my current MariaDB installation is using the default character set utf8mb4, either we need to reduce the default varchar() size (and accept there's a limit) or do something else.

**Comment by TomBZombie** [comment]
TODO: Have Maphper find the max key size  and set it

This will cause problems if we need to have a key larger than the max size. Maphper won't be able to extend the column size, though I'm not sure there's anything we can do about it. It would be better to have a check in place.

**Comment by TomBZombie** [comment]
@solleer  can you take a look at 1f87b1f3f8f5c27e790f19d568bde5a0ab02d233  and let me know if my workaround is ok.

I'm not really sure what this test `testMultiPkUnset` is supposed to be doing, shouldn't it just be doing `$this->assertEquals(0, count($mapper));`? As it stands, the callback function in array_reduce is never called because the array is empty, `$result` is set to `null` and the test fails because `count(null)` creates the error `count(): Parameter must be an array or an object that implements Countable`

**Comment by solleer** [comment]
The workaround seems ok.
I don't know what I was doing with those tests. They need to be fixed.

**Comment by TomBZombie** [comment]
I'll leave it as is for now. At the moment all tests are passing so I'll start working through some of the remaining issues.
