### ISSUE TITLE
Documentation - Advanced filters

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Maphper#6]
Add documentation for advanced filtering. AND/OR/NOT queries, LIKE, STARTS, etc... and grouping them together.

**Comment by solleer** [comment]
How is the advanced filtering done

**Comment by TomBZombie** [comment]
## Building advanced queries 

You can chain any query you like. Imagine a mapper for a table of products. To search for all products with a price between 50.00 and 99.00 OR on sale:

```php
use \Maphper\Maphper::FIND_OR;
use \Maphper\Maphper::FIND_AND;
use \Maphper\Maphper::FIND_LESS;
use \Maphper\Maphper::FIND_GREATER;

$products->filter([
	FIND_OR => [
		FIND_AND => [
			FIND_GREATER => [
				'price' => 50
			],
			FIND_LESS => [
				'price' => 100
			]			
		],
		'onSale' = 1
	]	
]);
```

Which will generate the query `SELECT * FROM products WHERE (price > 50 AND price < 100) OR onSale=1`

## IN() queries

Any value can take an array to find more than one record

```
$products->filter(['categoryId' => [1, 4, 6, 8]);
```

Which will generate `SELECT * FROM products WHERE categoryID IN(1, 4, 6, 8)`

**Comment by solleer** [comment]
Thank you so much
