### ISSUE TITLE
collection => Item - Add features to Collection part

### ISSUE THREAD

**Issue by pwFoo** [Level-2/Maphper#64]
Hi @TRPB,
I used Processwire with a awesome API and Selector feature. With powerful WireArray / PageArray (= Collection) and Page objects (= Items).

I read I can use "Concrete classes for mapped objects", what would be "Items" for me. 

To integrate additional / advanced find, filter, search features extend the Maphper class or is there another way as done with the "Item" return class?

**Comment by pwFoo** [comment]
The Collection part should have some nice features like 
- find()
- filter()
- next()
- prev()

The result of DataSource "query" should be such a Collection (optional?! like done with custom result class object?)

**Comment by TRPB** [comment]
Mapper already provides this feature. Use filters to search for specific data in a mapper:

```
$filteredBlogs = $blogs->filter(['date' => '2014-04-09']);
```

You can then loop over with `foreach`. It doesn't support `prev()` or next but you can use `->count()` and a for loop to acheive this

**Comment by pwFoo** [comment]
Hi,
how to build a complex filter like "between", "greater than" and "lesser than"?

**Comment by TRPB** [comment]
This needs better documentation but you can build advanced queries like this:

```php
use \Maphper\Maphper::FIND_OR;
use \Maphper\Maphper::FIND_AND;
use \Maphper\Maphper::FIND_LESS;
use \Maphper\Maphper::FIND_GREATER;

$products->filter([
    FIND_OR => [
        FIND_AND => [
            FIND_GREATER => [
                'price' => 50
            ],
            FIND_LESS => [
                'price' => 100
            ]           
        ],
        'onSale' = 1
    ]   
]);
```

**Comment by pwFoo** [comment]
Sounds great! 

Should be possible to extend Maphper class with additional methods if needed I think...
My custom Collection / Items setup should be base data handler for in memory array data AND database data with the same handling (add, search, filter, remove...).
Looks like Maphper IS exactly what I try to build with much more implemented **useful** additional features without the "bloated senseless" features other frameworks / classes deliver.

I really like the way you have built Maphper! 👍

**Comment by TRPB** [comment]
If you want a memory based mapper, you can easily add one by implementing the https://github.com/Level-2/Maphper/blob/master/Maphper/DataSource.php interface.

This would allow a RedisDataSource or MemcacheDataSource to be related to a MySQL table using the existing relations.

$mapper[123] might come from a database or memcache. 

Thanks, I'm glad you like it!

**Comment by pwFoo** [comment]
I found the mock.php datasource. It's something like my Collection => Items structure!

Is Mock DataSource full supported and could it be renamed in ArrayObject for example?
My custom projects started with a ArrayObject Collection of Item objects... That could be 1:1 ported to `\Maphper\DataSource\Mock` :)

**Comment by pwFoo** [comment]
filter ID with FIND_GREATER or FIND_LESSER doesn't work I think? But searching for a data field instead works fine with Mock with a simple test ("age" range between 20 and 30 years...).

But would be really great if you could rename it to for example ArrayObject similar to Database for a database backend like Mock uses ArrayObject as "backend"?

**Comment by TRPB** [comment]
The mock class was really there for just testing, it doesn't currently support filtering or any advanced usage beyond mocking the data storage.

**Comment by pwFoo** [comment]
Which advanced features do you mean? Filtering by fields seems to work? 

But it would be a nice base feature to just use a Array instead of a database backend for some basic stuff to do?

**Comment by pwFoo** [comment]
> The mock class was really there for just testing, it doesn't currently support filtering or any advanced usage beyond mocking the data storage.

Filtering with FIND_GREATER and FIND_LESSER was fine with my test. Looked in the code, but not see which features could be missing?
Wouldn't Mock / ArrayObject not a good example DataSource to understand how a DataSource works? 
I don't understand how and which features are implemented because of the different Database DataSource files. Maybe I missed / overlooked the important parts?

So I would love the Mock / ArrayObject to be feature complete or with a useful set of features and also to maybe better understand how the features implemented.

**Comment by pwFoo** [comment]
Get me right... I'm played with array search features the last days, but not so experienced programmer. I would try to implement the missing parts. But I would need some help to find where (methods?) and maybe how...

**Comment by pwFoo** [comment]
I tried it again with Mock and Database DataSource, but filter doesn't work anymore?
I played with my successfully tested filter from last test and also played around and compared to your example, but filter part of object remains empty.

**Comment by pwFoo** [comment]
Hi @TRPB,
instead of a PHP Array(Object) backend I thinking about a in memory sqlite databse for that case?

What do you think about? Would in memory sqlite be performant compared to an PHP Array(Object)?

SQLite would have all the nice filter / find features which ArrayObject / Mock haven't yet.

**Comment by TRPB** [comment]
Why do you need in-memory data? Surely the kind of data you're dealing with is persistent. Otherwise, you are creating a large/complex data structure then filtering it the same request so you're processing the same data multiple times: Once to sort it into the correct mapper, and once to filter it.

**Comment by pwFoo** [comment]
I think about runtime configs / Data

**Comment by TRPB** [comment]
do you have a practical example? Maphper isn't really designed for that and is probably overkill.

**Comment by pwFoo** [comment]
I have a script with simple event / hook handling. Events and hooks should be added to an Array(Object) and events should be searched / filtered for execution or sorted by hook priority.

Load json / xml / feed to a filterable / sortable array of objects and optionally save to db If needed / prepared.

**Comment by pwFoo** [comment]
> This needs better documentation but you can build advanced queries like this:
> 
> ```
> use \Maphper\Maphper::FIND_OR;
> use \Maphper\Maphper::FIND_AND;
> use \Maphper\Maphper::FIND_LESS;
> use \Maphper\Maphper::FIND_GREATER;
> 
> $products->filter([
>     FIND_OR => [
>         FIND_AND => [
>             FIND_GREATER => [
>                 'price' => 50
>             ],
>             FIND_LESS => [
>                 'price' => 100
>             ]           
>         ],
>         'onSale' = 1
>     ]   
> ]);
> ```

Could you add more documentation and examples about (complex) filters?

**Comment by pwFoo** [comment]
Moved to #71
